class_name CelebrationLines
extends RefCounted

const LINES := [
	"Beautifully done.",
	"That was smooth.",
	"You found it.",
	"Perfect path.",
	"Nicely traced.",
	"A lovely solve.",
	"Clean finish.",
	"Well played.",
	"Brilliant route.",
	"You made it.",
	"Everything clicks.",
	"Light restored.",
	"Puzzle cleared.",
	"Path complete.",
	"A clever turn.",
	"Bright thinking.",
	"Sharp eye.",
	"Great instincts.",
	"Nicely navigated.",
	"That flowed.",
	"So satisfying.",
	"A graceful finish.",
	"Spot on.",
	"Excellent work.",
	"You lit it up.",
	"Smooth moves.",
	"What a route.",
	"Wonderfully done.",
	"A neat solution.",
	"All aligned.",
	"Perfectly placed.",
	"You saw the way.",
	"A fine finish.",
	"Beautiful route.",
	"Just right.",
	"Cleverly done.",
	"The line lands.",
	"A bright finish.",
	"You nailed it.",
	"Lovely work.",
	"That fits.",
	"Pure precision.",
	"A perfect sweep.",
	"Nicely solved.",
	"You found the flow.",
	"A little magic.",
	"Right on track.",
	"Beautiful balance.",
	"The path shines.",
	"A clear win.",
	"All bright.",
	"You connected it.",
	"A satisfying solve.",
	"Well traced.",
	"Clever path.",
	"You kept your cool.",
	"The tiles agree.",
	"A smart finish.",
	"There it is.",
	"Made it glow.",
	"A lovely line.",
	"Brilliantly done.",
	"Puzzle complete.",
	"Nice and clean.",
	"You read it well.",
	"Beautiful timing.",
	"The light returns.",
	"A tidy triumph.",
	"That was elegant.",
	"Excellent path.",
	"A bright idea.",
	"You got there.",
	"All set.",
	"Simply brilliant.",
	"A smooth finish.",
	"That's the line.",
	"A perfect connection.",
	"Neatly done.",
	"You found the pattern.",
	"A glowing result.",
	"Your line worked.",
	"A clever crossing.",
	"Spotless finish.",
	"It all lines up.",
	"The board is bright.",
	"You made it shine.",
	"A smart route.",
	"Nice touch.",
	"That did it.",
	"Ready for more.",
	"One beautiful line.",
	"Great finish.",
	"You saw it.",
	"Everything glows.",
	"A graceful route.",
	"Nicely balanced.",
	"Just like that.",
	"A brilliant finish.",
	"Beautiful solve.",
	"You brought the light.",
]
